
#include "ShaderSemantics.h"

_VALUE_SEMANTIC VALUE_SEMANTIC[] =
{
	//{_VALUESEMANTIC_SPEC::VALSEM_NON 					,VALTYPE_NON,_VALUE_LEVEL_NON},
	{_VALUESEMANTIC_SPEC::VALSEM_VERTEX					,VALTYPE_VEC3,_VALUE_LEVEL_NON,"VALSEM_VERTEX"},
	{_VALUESEMANTIC_SPEC::VALSEM_NORMAL					,VALTYPE_VEC3,_VALUE_LEVEL_NON, "VALSEM_NORMAL"},
	{_VALUESEMANTIC_SPEC::VALSEM_BINORMAL				,VALTYPE_VEC3,_VALUE_LEVEL_NON, "VALSEM_BINORMAL"},
	{_VALUESEMANTIC_SPEC::VALSEM_TANGENT				,VALTYPE_VEC3,_VALUE_LEVEL_NON, "VALSEM_TANGENT"},
	{_VALUESEMANTIC_SPEC::VALSEM_TEXCOORD0				,VALTYPE_VEC3,_VALUE_LEVEL_NON, "VALSEM_TEXCOORD0"},
	{_VALUESEMANTIC_SPEC::VALSEM_TEXCOORD1				,VALTYPE_VEC3,_VALUE_LEVEL_NON, "VALSEM_TEXCOORD1"},
	{_VALUESEMANTIC_SPEC::VALSEM_WEIGHTOFS				,VALTYPE_FLOAT,_VALUE_LEVEL_NON, "VALSEM_WEIGHTOFS"},
	{_VALUESEMANTIC_SPEC::VALSEM_VERTEXID				,VALTYPE_FLOAT,_VALUE_LEVEL_NON, "VALSEM_VERTEXID"},
	{_VALUESEMANTIC_SPEC::VALSEM_COLOR                   ,VALTYPE_VEC3, _VALUE_LEVEL_NON, "VALSEM_COLOR"},

	{_VALUESEMANTIC_SPEC::VALSEM_INVVIEWPROJWORLDMX		,VALTYPE_MATRIX4X4,_VALUE_LEVEL_MODEL, "VALSEM_INVVIEWPROJWORLDMX"},
	{_VALUESEMANTIC_SPEC::VALSEM_INVVIEWWORLDMX			,VALTYPE_MATRIX4X4,_VALUE_LEVEL_MODEL, "VALSEM_INVVIEWWORLDMX"},
	{_VALUESEMANTIC_SPEC::VALSEM_WORLDVIEWPROJMX		,VALTYPE_MATRIX4X4,_VALUE_LEVEL_MODEL, "VALSEM_WORLDVIEWPROJMX"},
	{_VALUESEMANTIC_SPEC::VALSEM_VIEWWORLDMX            ,VALTYPE_MATRIX4X4,_VALUE_LEVEL_MODEL, "VALSEM_VIEWWORLDMX"},
	{_VALUESEMANTIC_SPEC::VALSEM_PROJVIEWWORLDMX        ,VALTYPE_MATRIX4X4,_VALUE_LEVEL_MODEL, "VALSEM_PROJVIEWWORLDMX"},
	{_VALUESEMANTIC_SPEC::VALSEM_VIEWMX					,VALTYPE_MATRIX4X4,_VALUE_LEVEL_ENGINE, "VALSEM_VIEWMX"},
	{_VALUESEMANTIC_SPEC::VALSEM_PROJMX					,VALTYPE_MATRIX4X4,_VALUE_LEVEL_ENGINE, "VALSEM_PROJMX"},
	{_VALUESEMANTIC_SPEC::VALSEM_UIPROJMX				,VALTYPE_MATRIX4X4,_VALUE_LEVEL_ENGINE, "VALSEM_UIPROJMX"},
	{_VALUESEMANTIC_SPEC::VALSEM_PROJVIEWMX             ,VALTYPE_MATRIX4X4,_VALUE_LEVEL_ENGINE, "VALSEM_PROJVIEWMX"},
	{_VALUESEMANTIC_SPEC::VALSEM_WORLDMX				,VALTYPE_MATRIX4X4,_VALUE_LEVEL_MODEL, "VALSEM_WORLDMX"},

	{_VALUESEMANTIC_SPEC::VALSEM_VIEWDIRMX				,VALTYPE_MATRIX4X4,_VALUE_LEVEL_ENGINE, "VALSEM_VIEWDIRMX"},
	{_VALUESEMANTIC_SPEC::VALSEM_VIEWINVMX				,VALTYPE_MATRIX4X4,_VALUE_LEVEL_ENGINE, "VALSEM_VIEWINVMX"},
	{_VALUESEMANTIC_SPEC::VALSEM_VIEWDIR				,VALTYPE_VEC3,_VALUE_LEVEL_ENGINE, "VALSEM_VIEWDIR"},
	{_VALUESEMANTIC_SPEC::VALSEM_VIEWPOS				,VALTYPE_VEC3,_VALUE_LEVEL_ENGINE, "VALSEM_VIEWPOS"},

	{_VALUESEMANTIC_SPEC::VALSEM_TEXTURE				,VALTYPE_TEXTURE,_VALUE_LEVEL_MESH, "VALSEM_TEXTURE"},
	{_VALUESEMANTIC_SPEC::VALSEM_SAMPLER			    ,VALTYPE_SAMPLER,_VALUE_LEVEL_MESH, "VALSEM_SAMPLER"},
	{_VALUESEMANTIC_SPEC::VALSEM_SAMPLER0				,VALTYPE_SAMPLER,_VALUE_LEVEL_MESH, "VALSEM_SAMPLER0"},
	{_VALUESEMANTIC_SPEC::VALSEM_SAMPLER1				,VALTYPE_SAMPLER,_VALUE_LEVEL_MESH, "VALSEM_SAMPLER1"},
	{_VALUESEMANTIC_SPEC::VALSEM_NORMALMAP				,VALTYPE_SAMPLER,_VALUE_LEVEL_MESH, "VALSEM_NORMALMAP"},
	{_VALUESEMANTIC_SPEC::VALSEM_SHADOWMAPS				,VALTYPE_SAMPLER,_VALUE_LEVEL_ENGINE, "VALSEM_SHADOWMAPS"},

	{_VALUESEMANTIC_SPEC::VALSEM_WEIGHTS				,VALTYPE_VEC4,_VALUE_LEVEL_MESH, "VALSEM_WEIGHTS"},
	{_VALUESEMANTIC_SPEC::VALSEM_WEIGHTTEX				,VALTYPE_SAMPLER,_VALUE_LEVEL_MESH, "VALSEM_WEIGHTTEX"},
	{_VALUESEMANTIC_SPEC::VALSEM_WEIGHTSIZE				,VALTYPE_FLOAT,_VALUE_LEVEL_MESH, "VALSEM_WEIGHTSIZE"},
	{_VALUESEMANTIC_SPEC::VALSEM_BONES					,VALTYPE_MATRIX4X4,_VALUE_LEVEL_MODEL, "VALSEM_BONES"},

	{_VALUESEMANTIC_SPEC::VALSEM_SHADOW_PROJWORLDMX		,VALTYPE_MATRIX4X4,_VALUE_LEVEL_MODEL, "VALSEM_SHADOW_PROJWORLDMX"},
	{_VALUESEMANTIC_SPEC::VALSEM_LIGHT_VIEWPROJWORLDMX	,VALTYPE_MATRIX4X4,_VALUE_LEVEL_MODEL, "VALSEM_LIGHT_VIEWPROJWORLDMX"},

	{_VALUESEMANTIC_SPEC::VALSEM_VEC4_MODEL_A			,VALTYPE_VEC4,_VALUE_LEVEL_MODEL, "VALSEM_VEC4_MODEL_A"},

	{_VALUESEMANTIC_SPEC::VALSEM_VEC4ARRAYL1			,VALTYPE_VEC4,_VALUE_LEVEL_MODEL, "VALSEM_VEC4ARRAYL1"},

	{_VALUESEMANTIC_SPEC::VALSEM_LIGHTVIEWPOS			,VALTYPE_VEC4,_VALUE_LEVEL_ENGINE, "VALSEM_LIGHTVIEWPOS"},
	{_VALUESEMANTIC_SPEC::VALSEM_LIGHTNUM				,VALTYPE_VEC4,_VALUE_LEVEL_ENGINE, "VALSEM_LIGHTNUM"},
	{_VALUESEMANTIC_SPEC::VALSEM_LIGHTPOSCONE			,VALTYPE_VEC4,_VALUE_LEVEL_ENGINE, "VALSEM_LIGHTPOSCONE"},
	{_VALUESEMANTIC_SPEC::VALSEM_LIGHTCOLORPOWER		,VALTYPE_VEC4,_VALUE_LEVEL_ENGINE, "VALSEM_LIGHTCOLORPOWER"},
	{_VALUESEMANTIC_SPEC::VALSEM_LIGHTDIRSPREAD			,VALTYPE_VEC4,_VALUE_LEVEL_ENGINE, "VALSEM_LIGHTDIRSPREAD"},
	{_VALUESEMANTIC_SPEC::VALSEM_LIGHTSPECMXARRAY	    ,VALTYPE_MATRIX4X4,_VALUE_LEVEL_ENGINE, "VALSEM_LIGHTSPECMXARRAY"},
	{_VALUESEMANTIC_SPEC::VALSEM_LIGHTSPECMX			,VALTYPE_MATRIX4X4,_VALUE_LEVEL_MESH, "VALSEM_LIGHTSPECMX"},
	{_VALUESEMANTIC_SPEC::VALSEM_VECTOR2_A				,VALTYPE_VEC2,_VALUE_LEVEL_MESH, "VALSEM_VECTOR2_A"},
	{_VALUESEMANTIC_SPEC::VALSEM_FLOAT_A				,VALTYPE_FLOAT,_VALUE_LEVEL_MESH, "VALSEM_FLOAT_A"},
	{_VALUESEMANTIC_SPEC::VALSEM_MESH_VEC2_A			,VALTYPE_VEC2,_VALUE_LEVEL_MESH, "VALSEM_MESH_VEC2_A"},
	{_VALUESEMANTIC_SPEC::VALSEM_MESH_VEC2_B			,VALTYPE_VEC2,_VALUE_LEVEL_MESH, "VALSEM_MESH_VEC2_B"},
	{_VALUESEMANTIC_SPEC::VALSEM_MESH_VEC2_C			,VALTYPE_VEC2,_VALUE_LEVEL_MESH, "VALSEM_MESH_VEC2_C"},
	{_VALUESEMANTIC_SPEC::VALSEM_MESH_VEC3_A			,VALTYPE_VEC3,_VALUE_LEVEL_MESH, "VALSEM_MESH_VEC3_A"},
	{_VALUESEMANTIC_SPEC::VALSEM_MESH_VEC3_B			,VALTYPE_VEC3,_VALUE_LEVEL_MESH, "VALSEM_MESH_VEC3_B"},
	{_VALUESEMANTIC_SPEC::VALSEM_MESH_VEC3_C			,VALTYPE_VEC3,_VALUE_LEVEL_MESH, "VALSEM_MESH_VEC3_C"},
	{_VALUESEMANTIC_SPEC::VALSEM_MESH_VEC4_A			,VALTYPE_VEC4,_VALUE_LEVEL_MESH, "VALSEM_MESH_VEC4_A"},
	{_VALUESEMANTIC_SPEC::VALSEM_MESH_VEC4_B			,VALTYPE_VEC4,_VALUE_LEVEL_MESH, "VALSEM_MESH_VEC4_B"},
	{_VALUESEMANTIC_SPEC::VALSEM_MESH_VEC4_C			,VALTYPE_VEC4,_VALUE_LEVEL_MESH, "VALSEM_MESH_VEC4_C"},

	{_VALUESEMANTIC_SPEC::VALSEM_MESH_REF_VEC4_A		,VALTYPE_REF_VEC4,_VALUE_LEVEL_MESH, "VALSEM_MESH_REF_VEC4_A"},

	{_VALUESEMANTIC_SPEC::VALSEM_MESH_UIREC_VEC4		,VALTYPE_VEC4,_VALUE_LEVEL_MESH, "VALSEM_MESH_UIREC_VEC4"},
	{_VALUESEMANTIC_SPEC::VALSEM_MESH_TEX_VEC4			,VALTYPE_VEC4,_VALUE_LEVEL_MESH, "VALSEM_MESH_TEX_VEC4"},
};

_VALUE_SEMANTIC* ShaderSemantics::values = VALUE_SEMANTIC;

//#include <engine/math/vector.h>
#include <glm/vec3.hpp>
#include <glm/vec2.hpp>
using namespace glm;

ShaderSemantics::_item_info VERT_ITEM_DEFS[10] = {
	ShaderSemantics::_item_info((int)sizeof(vec3) ,3),//VALSEM_VERTEX
	ShaderSemantics::_item_info((int)sizeof(vec3), 3),//VALSEM_NORMAL
	ShaderSemantics::_item_info((int)sizeof(vec3), 3),//VALSEM_BINORMAL
	ShaderSemantics::_item_info((int)sizeof(vec3), 3),//VALSEM_TANGENT
	ShaderSemantics::_item_info((int)sizeof(vec2), 2),//VALSEM_TEXCOORD0
	ShaderSemantics::_item_info((int)sizeof(vec2), 2),//VALSEM_TEXCOORD1
	ShaderSemantics::_item_info((int)sizeof(float), 1),//VALSEM_WEIGHTOFS
	ShaderSemantics::_item_info((int)sizeof(float), 1),//VALSEM_VERTEXID
	ShaderSemantics::_item_info((int)sizeof(vec3), 3)//VALSEM_COLOR
};

ShaderSemantics::_item_info* ShaderSemantics::vert_def = VERT_ITEM_DEFS;